
// Generated by ntoolkit/futures
package parser

import "ntoolkit/futures"


type DeferredTokens struct {
	DeferredValue futures.Promise
}

func (promise *DeferredTokens) init() {
	if promise.DeferredValue == nil {
		promise.DeferredValue = &futures.DeferredValue{}
	}
}

func (promise *DeferredTokens) Resolve(result *Tokens) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredTokens) Reject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}

func (promise *DeferredTokens) Errors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredTokens) Then(resolve func(*Tokens), reject func(error)) *DeferredTokens {
	promise.init()
	promise.DeferredValue.PThen(func(value interface{}) {
		if v, ok := value.(*Tokens); ok {
			resolve(v)
		} else {
		  panic("Invalid value used to resolve DeferredTokens")
		}
	}, reject)
	return promise
}

func (promise *DeferredTokens) PThen(result func(interface{}), reject func(error)) futures.Promise {
	promise.init()
	return promise.DeferredValue.PThen(result, reject)
}

func (promise *DeferredTokens) PErrors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredTokens) PResolve(result interface{}) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredTokens) PReject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}
